name: Report test results

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  report_test_results:
    name: Report test results
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Download test results
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          path: test_results
          pattern: test_results_*
          merge-multiple: true
      - name: List downloaded files
        run: ls -lR
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        with:
          files: "test_results/*.xml"
